### ISSUE TITLE
Getting Error ReferenceError: globalThis is not defined while using with Node 10.24.1 

### ISSUE THREAD

**Issue by nakulprosperoware** [pierrec/node-eval#32]
I have my node environment as 10.24.1 where I am facing this issue

`evalmachine.<anonymous>:1`
`Object.getOwnPropertyNames(globalThis)`

`ReferenceError: globalThis is not defined`
   ` at evalmachine.<anonymous>:1:28`
    `at Script.runInContext (vm.js:133:20)`
    `at Script.runInNewContext (vm.js:139:17)`
    `at Object.<anonymous> (C:\Users\NakulJhunjhunwala\Desktop\Node test\node_modules\eval\eval.js:17:4)`
    `at Module._compile (internal/modules/cjs/loader.js:778:30)`
    `at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)`
    `at Module.load (internal/modules/cjs/loader.js:653:32)`
    `at tryModuleLoad (internal/modules/cjs/loader.js:593:12)`
    `at Function.Module._load (internal/modules/cjs/loader.js:585:3)`
    `at Module.require (internal/modules/cjs/loader.js:692:17)`

**Comment by Josh-Cena** [comment]
Node 10 has long been EOL; you should not be using it and libraries implicitly do not support it.
